
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "./components/header/Header";
import AuthProvider from "./components/AuthProvider/AuthProvider";
import { ReduxProvider } from "./components/reduxProvider/reduxProvider";
import { store } from "@/store";
import "./reset.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Euphoria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <AuthProvider>
          <ReduxProvider >
            <Header />
            <div className="my-container">{children}</div>
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
